[package]
name = "liquid-help-md"
version = "0.26.1"
authors = ["Ed Page <eopage@gmail.com>"]
description = "Describe Liquid language via markdown"
repository = "https://github.com/cobalt-org/liquid-rust"
documentation = "https://docs.rs/liquid"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.60.0"  # MSRV
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[package.metadata.release]
pre-release-replacements = [
  {file="README.md", search="liquid-help-md = \".*\"", replace="liquid-help-md = \"{{version}}\"", exactly=1},
]

[dependencies]
liquid-core = { version = "^0.26.1", path = "../core" }
